### ISSUE TITLE
undefined method `deprecator' for ActiveSupport:Module

### ISSUE THREAD

**Issue by ameedsayeh** [bitrise-steplib/steps-cocoapods-install#101]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions, but found nothing relevant.
- Which version of the step is effected? 2.4.0
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NO

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

When executing Pod install step, the step fails with (undefined method `deprecator' for ActiveSupport:Module (NoMethodError))

### Bitrise info

- Log:

<details>
  <pre>
Installing cocoapods
Checking cocoapods 1.12.1 gem
Installing
$ gem "install" "cocoapods" "--no-document" "-v" "1.12.1"
$ asdf "reshim" "ruby"
cocoapods version:
$ pod "_1.12.1_" "--version"
/Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3/lib/active_support/core_ext/array/conversions.rb:108:in `<class:Array>': undefined method `deprecator' for ActiveSupport:Module (NoMethodError)
  deprecate to_default_s: :to_s, deprecator: ActiveSupport.deprecator
                                                          ^^^^^^^^^^^
Did you mean?  deprecate_constant
	from /Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3/lib/active_support/core_ext/array/conversions.rb:8:in `<top (required)>'
	from <internal:/Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods.rb:9:in `<top (required)>'
	from <internal:/Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/bin/pod:36:in `<top (required)>'
	from /Users/vagrant/.asdf/installs/ruby/3.2/bin/pod:25:in `load'
	from /Users/vagrant/.asdf/installs/ruby/3.2/bin/pod:25:in `<main>'
command failed, error: exit status 1
  </pre>
</details>

### Steps to reproduce

Just a regular run with Pod install.

This never happened before but suddenly started happening today.

I tried the solution listed here:
https://github.com/bitrise-steplib/steps-cocoapods-install/issues/100
But it fails while uninstalling activesupport

<details>
<pre>
+ gem uninstall activesupport
ERROR:  While executing gem ... (Gem::DependencyRemovalException)
    Uninstallation aborted due to dependent gem(s)
	/Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/3.2.0/rubygems/uninstaller.rb:156:in `uninstall_gem'
	/Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/3.2.0/rubygems/uninstaller.rb:144:in `uninstall'
	/Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/3.2.0/rubygems/commands/uninstall_command.rb:199:in `uninstall'
	/Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/3.2.0/rubygems/commands/uninstall_command.rb:185:in `uninstall_gem'
	/Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/3.2.0/rubygems/commands/uninstall_command.rb:179:in `block in uninstall_specific'
	/Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/3.2.0/rubygems/commands/uninstall_command.rb:171:in `each'
	/Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/3.2.0/rubygems/commands/uninstall_command.rb:171:in `uninstall_specific'
	/Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/3.2.0/rubygems/commands/uninstall_command.rb:137:in `execute'
	/Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/3.2.0/rubygems/command.rb:328:in `invoke_with_build_args'
	/Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/3.2.0/rubygems/command_manager.rb:253:in `invoke_command'
	/Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/3.2.0/rubygems/command_manager.rb:193:in `process_args'
	/Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/3.2.0/rubygems/command_manager.rb:151:in `run'
	/Users/vagrant/.asdf/installs/ruby/3.2.3/lib/ruby/3.2.0/rubygems/gem_runner.rb:52:in `run'
	/Users/vagrant/.asdf/installs/ruby/3.2/bin/gem:10:in `<main>'
</pre>
</details>

**Comment by ameedsayeh** [comment]
Updating Cocoapods version in the `Podfile.lock` solved the issue:
Apple Silicon:
`brew install cocoapods`
Intel:
`sudo gem install cocoapods`
1.15.2 worked for me! probably anything >= 1.14.0 should solve it as here: 
https://github.com/CocoaPods/CocoaPods/pull/12082
