### ISSUE TITLE
failed to load command: pod, Can't find executable pod for gem cocoapods. cocoapods

### ISSUE THREAD

**Issue by kyle-ssg** [bitrise-steplib/steps-cocoapods-install#87]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.3
- Is the issue reproducible with the latest version? YES 
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES / NO / NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

Trying out Bitrsise I get the following on this step 

```
$ bundle "_2.2.27_" "exec" "pod" "--version"
bundler: failed to load command: pod (/Users/vagrant/.rbenv/versions/2.6.9/bin/pod)
/Users/vagrant/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/rubygems_integration.rb:364:in `block in replace_bin_path': can't find executable pod for gem cocoapods. cocoapods is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)

```

### Bitrise info

- Build URL: [_Please share the build URL with us._](https://app.bitrise.io/build/9a40e4d1-a394-442f-bde4-5c7f7527d8aa)
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: 

```
$ bundle "_2.2.27_" "exec" "pod" "--version"
bundler: failed to load command: pod (/Users/vagrant/.rbenv/versions/2.6.9/bin/pod)
/Users/vagrant/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/rubygems_integration.rb:364:in `block in replace_bin_path': can't find executable pod for gem cocoapods. cocoapods is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)

```

**Comment by kyle-ssg** [comment]
This was due to the project having a gemfile.lock, removing it fixed it
